### ISSUE TITLE
 the gain compensation values of the two images obtained from the file gainCompensation. m are equal

### ISSUE THREAD

**Issue by zking4905** [preethamam/AutoPanoStitch#1]
Hello, I read your code recently. When I use two images for stitching, I find that the gain compensation values of the two images obtained from the file gainCompensation. m are equal. When stitching multiple images, the gain compensation values of each image are different. In theory, when stitching two images, the gain compensation value should also be different. Can you test whether there is the problem I said?

**Comment by preethamam** [comment]
Generally, gain values are close to 1 (unless there is a huge exposure difference) and most of the time they are close to each other. Could you please share before and after images and their gain values?

**Comment by zking4905** [comment]
Thanks for your reply. In the attachment, the test image I used has obvious exposure difference between images, and the gain compensation value is [0.6270 0.6485 0.7317; 0.6270 0.6485 0.7317]




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "preethamam/AutomaticPanoramicImageStitching-AutoPanoStitch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 中午11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [preethamam/AutomaticPanoramicImageStitching-AutoPanoStitch]  the gain compensation values of the two images obtained from the file gainCompensation. m are equal (Issue #1)





 
Generally, gain values are close to 1 (unless there is a huge exposure difference) and most of the time they are close to each other. Could you please share before and after images and their gain values?

**Comment by preethamam** [comment]
Can you please share the images it would be helpful for debugging?

**Comment by zking4905** [comment]
The image is in the attachment. If you don't see it, I will email you.










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "preethamam/AutomaticPanoramicImageStitching-AutoPanoStitch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 中午11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [preethamam/AutomaticPanoramicImageStitching-AutoPanoStitch]  the gain compensation values of the two images obtained from the file gainCompensation. m are equal (Issue #1)





 
Can you please share the images it would be helpful for debugging?

**Comment by preethamam** [comment]
I don't see it in the attachment. Are you sure you attached them? If so, that is strange.

**Comment by zking4905** [comment]
I sent another set of test images, and the calculated gain compensation values of the two images are also the same. The gain compensation values are [0.9897 0.9912 0.9919; 0.9897 0.9912 0.9919]






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "preethamam/AutomaticPanoramicImageStitching-AutoPanoStitch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [preethamam/AutomaticPanoramicImageStitching-AutoPanoStitch]  the gain compensation values of the two images obtained from the file gainCompensation. m are equal (Issue #1)





 
I don't see it in the attachment. Are you sure you attached them? If so, that is strange.

**Comment by preethamam** [comment]
I still don't see the attached images.

**Comment by zking4905** [comment]
I sent it by QQ email. The image is in the attachment of QQ email. Still don't see the images?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "preethamam/AutomaticPanoramicImageStitching-AutoPanoStitch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 中午11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [preethamam/AutomaticPanoramicImageStitching-AutoPanoStitch]  the gain compensation values of the two images obtained from the file gainCompensation. m are equal (Issue #1)





 
I still don't see the attached images.

**Comment by preethamam** [comment]
No, I don't see. Could you please attach it to GitHub? Hopefully, the dimensions remain the same and it doesn't compress. Please send both sets of images.

**Comment by preethamam** [comment]
Gains close to unity are fine but need to see why they are the same for all images. Please refer to the attached paper. As it is mentioned, "Also, since g = 0 is an optimal solution to the problem, we add a prior term to keep the gains close to unity."

[ijcv2007.pdf](https://github.com/preethamam/AutomaticPanoramicImageStitching-AutoPanoStitch/files/10408029/ijcv2007.pdf)

**Comment by zking4905** [comment]
I upload the image to github. The link is: https://github.com/zking4905/test_imgs

**Comment by preethamam** [comment]
Thanks, I got them. I will look at it.

**Comment by zking4905** [comment]
In theory, I think the gain compensation value obtained should be different, although it can be close. If the gain compensation values are equal, it is difficult to adjust the images with different brightness and color differences to the same level. Whether there are errors in your code.

**Comment by preethamam** [comment]
@zking4905, the gain compensation issue has been fixed in the latest release and in the main. Therefore, I will be closing this issue.
