### ISSUE TITLE
Can not find detectSIFTFeatures function？

### ISSUE THREAD

**Issue by zyy839** [preethamam/AutoPanoStitch#2]
Main_AutoPanoStitch (line 62)
 [keypoints, allDescriptors, images, imageinfo, imageFocals, numImg]
    = featureMatching(input, imgSetVector, myImg);

 featureMatching>(parfor body) (line 44)
        [descriptors, points] = getFeaturePoints(input, image);

**Comment by preethamam** [comment]
It requires the [MATLAB Computer Vision Toolbox.](https://www.mathworks.com/help/vision/ref/detectsiftfeatures.html) If the MATLAB toolbox is unavailable, you can use the [VL Feat toolbox](https://www.vlfeat.org/matlab/vl_sift.html). However, this requires a small change in the code.
