### ISSUE TITLE
Error while using your amazing code 

### ISSUE THREAD

**Issue by MedIWA** [preethamam/AutoPanoStitch#3]
Hallo Sir,

I am getting this error while running your main file, why is this happening ?, What should I do to fix it, I am totally new in MATLAB.

**Error:**
Starting parallel pool (parpool) using the 'Processes' profile ...
Error using parpool
Too many workers requested. The cluster "Processes" has the NumWorkers property set to a maximum of 14 workers but 32 workers were requested. Either request a number of workers less than NumWorkers, or
increase the value of the NumWorkers property for the cluster (up to a maximum of 512 for the Local cluster).

Error in Main_AutoPanoStitch (line 36)
    parpool(input.numCores);
 
Thanks a lot in advanced.

**Comment by preethamam** [comment]
Hello @MedIWA, 

Please change `input.numbers = 32;` in the `Inputs.m` input file to your worker's number, i.e., 14 or less.
